spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: daitou666
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall  # 底层开启功能，stat（sql监控），wall（防火墙）
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      stat-view-servlet:  # 配置监控页功能
        enabled: true
        login-username: 蔡徐坤  #设置登录的用户名
        login-password: 123456 #设置登录的密码
        allow: 127.0.0.1  #设置允许登录的用户
        reset-enable: false #设置页面是否有重置按钮
      web-stat-filter: # 监控web
        enabled: true
        url-pattern: /*  #监控所有的路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  #设置除去监控的文件
      aop-patterns: com.atguigu.admin.*  #监控SpringBean



  #    type: com.zaxxer.hikari.HikariDataSource
  jdbc:
    template:
      query-timeout: 3

  application:
    name: boot-05-web-admin
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*  #指定映射文件的路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

    # 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中了。
    #并且，config-location:不能和configuration共存
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#management开头的是所有actuator的所的初始配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有的监控端点,此处关闭
    web:
      exposure:
        include: '*'  #以web的方式暴露所有的监控端点
  endpoint:
    health:
      show-details: always
      enabled: true  #开启健康节点
    info:
      enabled: true  #开启info节点
    beans:
      enabled: true  #开启beans节点
    metrics:
      enabled: true
info:
  appName: boot-cxkApp
  appversion: 2.5
  mavenProjectName: boot-05-web-admin
  mavenProjectVersion: 0.0.1-SNAPSHOT
